"""initial clean

Revision ID: 9839f5be9f41
Revises: 
Create Date: 2025-11-14 19:23:05.309612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9839f5be9f41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['matiere.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('room_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['matiere.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_token')
    )
    op.create_table('room_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bug_reports')
    op.drop_table('user')
    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint('commentaire_auteur_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('commentaire_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['auteur_id'], ['id'])

    with op.batch_alter_table('devoir', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('filiere',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('annee',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('devoir_vu', schema=None) as batch_op:
        batch_op.drop_constraint('_devoir_etudiant_uc', type_='unique')
        batch_op.drop_constraint('devoir_vu_devoir_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('devoir_vu_etudiant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'etudiant', ['etudiant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'devoir', ['devoir_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('emploi_temps', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('jour',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('salle',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('_enseignant_jour_creneau_uc', ['enseignant_id', 'jour', 'heure_debut', 'heure_fin'])
        batch_op.create_unique_constraint('_salle_jour_creneau_uc', ['salle', 'jour', 'heure_debut', 'heure_fin'])

    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.alter_column('specialite',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('filieres_enseignees',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_enseignant_user', ['user_id'])
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint('etudiant_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('filiere_admin', schema=None) as batch_op:
        batch_op.drop_constraint('filiere_admin_filiere_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('filiere_admin_enseignant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'enseignant', ['enseignant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'filiere', ['filiere_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique message identifier',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID of the message sender',
               existing_nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID of the message receiver',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Message content (text)',
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the message was sent (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the message has been read by the receiver',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('ix_message_unread', postgresql_where='(is_read = false)')
        batch_op.drop_constraint('fk_message_sender', type_='foreignkey')
        batch_op.drop_constraint('fk_message_receiver', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Stores real-time chat messages between users'
    )

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_evaluation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('date_evaluation',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('element_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_constraint('password_reset_token_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('piece_jointe', schema=None) as batch_op:
        batch_op.alter_column('type_fichier',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('taille',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('piece_jointe_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique de la session',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('etudiant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Référence à l'étudiant propriétaire de la session",
               existing_nullable=False)
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Référence à la matière étudiée (peut être NULL)',
               existing_nullable=True)
        batch_op.alter_column('date_debut',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date et heure de début de la session',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_fin',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date et heure de fin de la session',
               existing_nullable=True)
        batch_op.alter_column('duree_prevue',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Durée prévue de la session en minutes (par défaut 25)',
               existing_nullable=False,
               existing_server_default=sa.text('25'))
        batch_op.alter_column('duree_reelle',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Durée réelle de la session en minutes',
               existing_nullable=True)
        batch_op.alter_column('type_session',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Type de session: 'travail' ou 'pause'",
               existing_nullable=False,
               existing_server_default=sa.text("'travail'::character varying"))
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Statut: 'en_cours', 'terminee', ou 'interrompue'",
               existing_nullable=False,
               existing_server_default=sa.text("'en_cours'::character varying"))
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Titre/nom de la session',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description ou notes sur la session',
               existing_nullable=True)
        batch_op.alter_column('tache_associee',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Tâche ou devoir associé à la session',
               existing_nullable=True)
        batch_op.alter_column('pause_prise',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique si la pause a été prise après cette session',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('duree_pause',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Durée de la pause en minutes',
               existing_nullable=True)
        batch_op.alter_column('nombre_interruptions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Nombre d'interruptions pendant la session",
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('niveau_concentration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Auto-évaluation du niveau de concentration (1-5)',
               existing_nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_modification',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment="Date de dernière modification de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_pomodoro_date_debut')
        batch_op.drop_index('idx_pomodoro_etudiant')
        batch_op.drop_index('idx_pomodoro_etudiant_date')
        batch_op.drop_index('idx_pomodoro_matiere')
        batch_op.drop_index('idx_pomodoro_statut')
        batch_op.drop_index('idx_pomodoro_type')
        batch_op.create_index(batch_op.f('ix_pomodoro_sessions_etudiant_id'), ['etudiant_id'], unique=False)
        batch_op.create_foreign_key(None, 'etudiant', ['etudiant_id'], ['id'])
        batch_op.create_foreign_key(None, 'matiere', ['matiere_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment="Table pour stocker les sessions d'étude avec la technique Pomodoro"
    )

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_auteur_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['auteur_id'], ['id'])

    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.alter_column('date_cours',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('heure_debut',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('heure_fin',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('heure_marquee',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_unique_constraint('_etudiant_matiere_date_heure_uc', ['etudiant_id', 'matiere_id', 'date_cours', 'heure_debut'])
        batch_op.create_foreign_key(None, 'enseignant', ['enseignant_id'], ['id'])
        batch_op.drop_column('date_presence')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teacher_profile_update_request', schema=None) as batch_op:
        batch_op.alter_column('filieres_enseignees',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='FiliŠres enseign‚es au format JSON ou CSV',
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut de la demande: en_attente, approuve, rejete',
               existing_nullable=True,
               existing_server_default=sa.text("'en_attente'::character varying"))
        batch_op.drop_index('idx_teacher_profile_update_request_date_creation')
        batch_op.drop_index('idx_teacher_profile_update_request_statut')
        batch_op.drop_index('idx_teacher_profile_update_request_user_id')
        batch_op.drop_constraint('teacher_profile_update_request_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Demandes de modification du profil enseignant soumises … approbation admin'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile_update_request', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Demandes de modification du profil enseignant soumises … approbation admin',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teacher_profile_update_request_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_teacher_profile_update_request_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_teacher_profile_update_request_statut', ['statut'], unique=False)
        batch_op.create_index('idx_teacher_profile_update_request_date_creation', ['date_creation'], unique=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut de la demande: en_attente, approuve, rejete',
               existing_nullable=True,
               existing_server_default=sa.text("'en_attente'::character varying"))
        batch_op.alter_column('filieres_enseignees',
               existing_type=sa.VARCHAR(length=500),
               comment='FiliŠres enseign‚es au format JSON ou CSV',
               existing_nullable=True)

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_presence', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_etudiant_matiere_date_heure_uc', type_='unique')
        batch_op.alter_column('heure_marquee',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('heure_fin',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('heure_debut',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('date_cours',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_auteur_id_fkey', 'user', ['auteur_id'], ['id'])

    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.create_table_comment(
        "Table pour stocker les sessions d'étude avec la technique Pomodoro",
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pomodoro_sessions_etudiant_id'))
        batch_op.create_index('idx_pomodoro_type', ['type_session'], unique=False)
        batch_op.create_index('idx_pomodoro_statut', ['statut'], unique=False)
        batch_op.create_index('idx_pomodoro_matiere', ['matiere_id'], unique=False)
        batch_op.create_index('idx_pomodoro_etudiant_date', ['etudiant_id', 'date_debut'], unique=False)
        batch_op.create_index('idx_pomodoro_etudiant', ['etudiant_id'], unique=False)
        batch_op.create_index('idx_pomodoro_date_debut', ['date_debut'], unique=False)
        batch_op.alter_column('date_modification',
               existing_type=postgresql.TIMESTAMP(),
               comment="Date de dernière modification de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('niveau_concentration',
               existing_type=sa.INTEGER(),
               comment='Auto-évaluation du niveau de concentration (1-5)',
               existing_nullable=True)
        batch_op.alter_column('nombre_interruptions',
               existing_type=sa.INTEGER(),
               comment="Nombre d'interruptions pendant la session",
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('duree_pause',
               existing_type=sa.INTEGER(),
               comment='Durée de la pause en minutes',
               existing_nullable=True)
        batch_op.alter_column('pause_prise',
               existing_type=sa.BOOLEAN(),
               comment='Indique si la pause a été prise après cette session',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('tache_associee',
               existing_type=sa.VARCHAR(length=200),
               comment='Tâche ou devoir associé à la session',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='Description ou notes sur la session',
               existing_nullable=True)
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=200),
               comment='Titre/nom de la session',
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment="Statut: 'en_cours', 'terminee', ou 'interrompue'",
               existing_nullable=False,
               existing_server_default=sa.text("'en_cours'::character varying"))
        batch_op.alter_column('type_session',
               existing_type=sa.VARCHAR(length=20),
               comment="Type de session: 'travail' ou 'pause'",
               existing_nullable=False,
               existing_server_default=sa.text("'travail'::character varying"))
        batch_op.alter_column('duree_reelle',
               existing_type=sa.INTEGER(),
               comment='Durée réelle de la session en minutes',
               existing_nullable=True)
        batch_op.alter_column('duree_prevue',
               existing_type=sa.INTEGER(),
               comment='Durée prévue de la session en minutes (par défaut 25)',
               existing_nullable=False,
               existing_server_default=sa.text('25'))
        batch_op.alter_column('date_fin',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date et heure de fin de la session',
               existing_nullable=True)
        batch_op.alter_column('date_debut',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date et heure de début de la session',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               comment='Référence à la matière étudiée (peut être NULL)',
               existing_nullable=True)
        batch_op.alter_column('etudiant_id',
               existing_type=sa.INTEGER(),
               comment="Référence à l'étudiant propriétaire de la session",
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique de la session',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('piece_jointe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('piece_jointe_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.alter_column('taille',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_fichier',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('password_reset_token_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('element_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('date_evaluation',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('type_evaluation',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores real-time chat messages between users',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_message_receiver', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_message_sender', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_message_unread', ['receiver_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               comment='Whether the message has been read by the receiver',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the message was sent (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               comment='Message content (text)',
               existing_nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               comment='User ID of the message receiver',
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               comment='User ID of the message sender',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='Unique message identifier',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('filiere_admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('filiere_admin_enseignant_id_fkey', 'enseignant', ['enseignant_id'], ['id'])
        batch_op.create_foreign_key('filiere_admin_filiere_id_fkey', 'filiere', ['filiere_id'], ['id'])

    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('etudiant_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('enseignant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_enseignant_user', type_='unique')
        batch_op.alter_column('filieres_enseignees',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('specialite',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('emploi_temps', schema=None) as batch_op:
        batch_op.drop_constraint('_salle_jour_creneau_uc', type_='unique')
        batch_op.drop_constraint('_enseignant_jour_creneau_uc', type_='unique')
        batch_op.alter_column('salle',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('jour',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('devoir_vu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('devoir_vu_etudiant_id_fkey', 'etudiant', ['etudiant_id'], ['id'])
        batch_op.create_foreign_key('devoir_vu_devoir_id_fkey', 'devoir', ['devoir_id'], ['id'])
        batch_op.create_unique_constraint('_devoir_etudiant_uc', ['devoir_id', 'etudiant_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('devoir', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('annee',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('filiere',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('titre',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('commentaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('commentaire_post_id_fkey', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('commentaire_auteur_id_fkey', 'user', ['auteur_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date_naissance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sexe', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo_profil', sa.VARCHAR(length=255), server_default=sa.text("'default.jpg'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('bug_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('steps_to_reproduce', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bug_reports_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bug_reports_pkey')
    )
    op.drop_table('room_participants')
    op.drop_table('room_invitations')
    op.drop_table('room_activity_logs')
    op.drop_table('rooms')
    op.drop_table('inscriptions')
    # ### end Alembic commands ###
