"""new

Revision ID: 14b7d61e5a0c
Revises: 231f4bcd9c21
Create Date: 2026-01-10 18:27:26.149705

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14b7d61e5a0c"
down_revision = "231f4bcd9c21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add column as nullable first
    with op.batch_alter_table("matiere", schema=None) as batch_op:
        batch_op.add_column(sa.Column("semestre", sa.Integer(), nullable=True))

    # 2. Populate existing rows with default value
    op.execute("UPDATE matiere SET semestre = 1 WHERE semestre IS NULL")

    # 3. Alter column to be not null
    with op.batch_alter_table("matiere", schema=None) as batch_op:
        batch_op.alter_column("semestre", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matiere", schema=None) as batch_op:
        batch_op.drop_column("semestre")

    # ### end Alembic commands ###
